/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Remotion": {
      "bucketName": string
      "functionName": string
      "region": string
      "siteUrl": string
      "type": "sst.sst.Linkable"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}